### ISSUE TITLE
The code is not properly structured 

### ISSUE THREAD

**Issue by prantik1998** [ofir-reich/seir-graph#1]
There are too many lines of code in a single file and I fell this makes the code unreadabe.

**Comment by ofir-reich** [comment]
I'm happy to accept pull requests if you have ideas for refactoring or splitting into multiple files.
I also recommend [SEIRS+](https://github.com/ryansmcgee/seirsplus) if you're looking for SEIR code.

**Comment by prantik1998** [comment]
Yes sir I have can I give a pull request.Can you please make me a contributor
