### ISSUE TITLE
how to get the animation using this code?

### ISSUE THREAD

**Issue by 15921483570** [ofir-reich/seir-graph#2]
may i know how to get the animation using this code?

i tried to run simulation() in seir.py, but no graph shows.

many thanks!

**Comment by ofir-reich** [comment]
The animation is not generated by the code. It was done manually as an illustration. It was composed using Google Draw to create the individual images, and then they were stringed into a GIF. If you just want the animation file, you can find the animated GIF file in the repo.

Good luck!
